package com.example.polynation;

import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

public class Countrynamemapper {
    private static final Map<String, String> RU_TO_ISO3 = new HashMap<>();
    private static final Map<String, String> ISO3_TO_ISO2 = new HashMap<>();

    static {
        RU_TO_ISO3.put("Австралия", "AUS");
        RU_TO_ISO3.put("Австрия", "AUT");
        RU_TO_ISO3.put("Азербайджан", "AZE");
        RU_TO_ISO3.put("Албания", "ALB");
        RU_TO_ISO3.put("Алжир", "DZA");
        RU_TO_ISO3.put("Ангола", "AGO");
        RU_TO_ISO3.put("Андорра", "AND");
        RU_TO_ISO3.put("Антигуа и Барбуда", "ATG");
        RU_TO_ISO3.put("Аргентина", "ARG");
        RU_TO_ISO3.put("Армения", "ARM");
        RU_TO_ISO3.put("Афганистан", "AFG");
        RU_TO_ISO3.put("Багамы", "BHS");
        RU_TO_ISO3.put("Бангладеш", "BGD");
        RU_TO_ISO3.put("Барбадос", "BRB");
        RU_TO_ISO3.put("Бахрейн", "BHR");
        RU_TO_ISO3.put("Беларусь", "BLR");
        RU_TO_ISO3.put("Белоруссия", "BLR");
        RU_TO_ISO3.put("Белиз", "BLZ");
        RU_TO_ISO3.put("Бельгия", "BEL");
        RU_TO_ISO3.put("Бенин", "BEN");
        RU_TO_ISO3.put("Болгария", "BGR");
        RU_TO_ISO3.put("Боливия", "BOL");
        RU_TO_ISO3.put("Босния и Герцеговина", "BIH");
        RU_TO_ISO3.put("Ботсвана", "BWA");
        RU_TO_ISO3.put("Бразилия", "BRA");
        RU_TO_ISO3.put("Бруней", "BRN");
        RU_TO_ISO3.put("Буркина-Фасо", "BFA");
        RU_TO_ISO3.put("Бурунди", "BDI");
        RU_TO_ISO3.put("Бутан", "BTN");
        RU_TO_ISO3.put("Вануату", "VUT");
        RU_TO_ISO3.put("Ватикан", "VAT");
        RU_TO_ISO3.put("Великобритания", "GBR");
        RU_TO_ISO3.put("Венгрия", "HUN");
        RU_TO_ISO3.put("Венесуэла", "VEN");
        RU_TO_ISO3.put("Восточный Тимор", "TLS");
        RU_TO_ISO3.put("Тимор-Лесте", "TLS");
        RU_TO_ISO3.put("Вьетнам", "VNM");
        RU_TO_ISO3.put("Габон", "GAB");
        RU_TO_ISO3.put("Гаити", "HTI");
        RU_TO_ISO3.put("Гайана", "GUY");
        RU_TO_ISO3.put("Гамбия", "GMB");
        RU_TO_ISO3.put("Гана", "GHA");
        RU_TO_ISO3.put("Гватемала", "GTM");
        RU_TO_ISO3.put("Гвинея", "GIN");
        RU_TO_ISO3.put("Гвинея-Бисау", "GNB");
        RU_TO_ISO3.put("Германия", "DEU");
        RU_TO_ISO3.put("Гондурас", "HND");
        RU_TO_ISO3.put("Гренада", "GRD");
        RU_TO_ISO3.put("Греция", "GRC");
        RU_TO_ISO3.put("Грузия", "GEO");
        RU_TO_ISO3.put("Дания", "DNK");
        RU_TO_ISO3.put("Джибути", "DJI");
        RU_TO_ISO3.put("Доминика", "DMA");
        RU_TO_ISO3.put("Доминиканская Республика", "DOM");
        RU_TO_ISO3.put("Египет", "EGY");
        RU_TO_ISO3.put("Замбия", "ZMB");
        RU_TO_ISO3.put("Зимбабве", "ZWE");
        RU_TO_ISO3.put("Израиль", "ISR");
        RU_TO_ISO3.put("Индия", "IND");
        RU_TO_ISO3.put("Индонезия", "IDN");
        RU_TO_ISO3.put("Иордания", "JOR");
        RU_TO_ISO3.put("Ирак", "IRQ");
        RU_TO_ISO3.put("Иран", "IRN");
        RU_TO_ISO3.put("Ирландия", "IRL");
        RU_TO_ISO3.put("Исландия", "ISL");
        RU_TO_ISO3.put("Испания", "ESP");
        RU_TO_ISO3.put("Италия", "ITA");
        RU_TO_ISO3.put("Йемен", "YEM");
        RU_TO_ISO3.put("Кабо-Верде", "CPV");
        RU_TO_ISO3.put("Казахстан", "KAZ");
        RU_TO_ISO3.put("Камбоджа", "KHM");
        RU_TO_ISO3.put("Камерун", "CMR");
        RU_TO_ISO3.put("Канада", "CAN");
        RU_TO_ISO3.put("Катар", "QAT");
        RU_TO_ISO3.put("Кения", "KEN");
        RU_TO_ISO3.put("Кипр", "CYP");
        RU_TO_ISO3.put("Кирибати", "KIR");
        RU_TO_ISO3.put("Китай", "CHN");
        RU_TO_ISO3.put("Колумбия", "COL");
        RU_TO_ISO3.put("Коморы", "COM");
        RU_TO_ISO3.put("Конго", "COG");
        RU_TO_ISO3.put("ДР Конго", "COD");
        RU_TO_ISO3.put("Демократическая Республика Конго", "COD");
        RU_TO_ISO3.put("Корея (КНДР)", "PRK");
        RU_TO_ISO3.put("КНДР", "PRK");
        RU_TO_ISO3.put("Северная Корея", "PRK");
        RU_TO_ISO3.put("Южная Корея", "KOR");
        RU_TO_ISO3.put("Республика Корея", "KOR");
        RU_TO_ISO3.put("Коста-Рика", "CRI");
        RU_TO_ISO3.put("Кот-д'Ивуар", "CIV");
        RU_TO_ISO3.put("Куба", "CUB");
        RU_TO_ISO3.put("Кувейт", "KWT");
        RU_TO_ISO3.put("Кыргызстан", "KGZ");
        RU_TO_ISO3.put("Киргизия", "KGZ");
        RU_TO_ISO3.put("Лаос", "LAO");
        RU_TO_ISO3.put("Латвия", "LVA");
        RU_TO_ISO3.put("Лесото", "LSO");
        RU_TO_ISO3.put("Либерия", "LBR");
        RU_TO_ISO3.put("Ливан", "LBN");
        RU_TO_ISO3.put("Ливия", "LBY");
        RU_TO_ISO3.put("Литва", "LTU");
        RU_TO_ISO3.put("Лихтенштейн", "LIE");
        RU_TO_ISO3.put("Люксембург", "LUX");
        RU_TO_ISO3.put("Маврикий", "MUS");
        RU_TO_ISO3.put("Мавритания", "MRT");
        RU_TO_ISO3.put("Мадагаскар", "MDG");
        RU_TO_ISO3.put("Малави", "MWI");
        RU_TO_ISO3.put("Малайзия", "MYS");
        RU_TO_ISO3.put("Мальдивы", "MDV");
        RU_TO_ISO3.put("Мали", "MLI");
        RU_TO_ISO3.put("Мальта", "MLT");
        RU_TO_ISO3.put("Марокко", "MAR");
        RU_TO_ISO3.put("Маршалловы Острова", "MHL");
        RU_TO_ISO3.put("Мексика", "MEX");
        RU_TO_ISO3.put("Микронезия", "FSM");
        RU_TO_ISO3.put("Мозамбик", "MOZ");
        RU_TO_ISO3.put("Молдова", "MDA");
        RU_TO_ISO3.put("Монако", "MCO");
        RU_TO_ISO3.put("Монголия", "MNG");
        RU_TO_ISO3.put("Мьянма", "MMR");
        RU_TO_ISO3.put("Намибия", "NAM");
        RU_TO_ISO3.put("Науру", "NRU");
        RU_TO_ISO3.put("Непал", "NPL");
        RU_TO_ISO3.put("Нигер", "NER");
        RU_TO_ISO3.put("Нигерия", "NGA");
        RU_TO_ISO3.put("Нидерланды", "NLD");
        RU_TO_ISO3.put("Никарагуа", "NIC");
        RU_TO_ISO3.put("Новая Зеландия", "NZL");
        RU_TO_ISO3.put("Норвегия", "NOR");
        RU_TO_ISO3.put("ОАЭ", "ARE");
        RU_TO_ISO3.put("Объединённые Арабские Эмираты", "ARE");
        RU_TO_ISO3.put("Оман", "OMN");
        RU_TO_ISO3.put("Пакистан", "PAK");
        RU_TO_ISO3.put("Палау", "PLW");
        RU_TO_ISO3.put("Панама", "PAN");
        RU_TO_ISO3.put("Папуа — Новая Гвинея", "PNG");
        RU_TO_ISO3.put("Папуа-Новая Гвинея", "PNG");
        RU_TO_ISO3.put("Парагвай", "PRY");
        RU_TO_ISO3.put("Перу", "PER");
        RU_TO_ISO3.put("Польша", "POL");
        RU_TO_ISO3.put("Португалия", "PRT");
        RU_TO_ISO3.put("Россия", "RUS");
        RU_TO_ISO3.put("Руанда", "RWA");
        RU_TO_ISO3.put("Румыния", "ROU");
        RU_TO_ISO3.put("Сальвадор", "SLV");
        RU_TO_ISO3.put("Самоа", "WSM");
        RU_TO_ISO3.put("Сан-Марино", "SMR");
        RU_TO_ISO3.put("Сан-Томе и Принсипи", "STP");
        RU_TO_ISO3.put("Саудовская Аравия", "SAU");
        RU_TO_ISO3.put("Свазиленд", "SWZ");
        RU_TO_ISO3.put("Эсватини", "SWZ");
        RU_TO_ISO3.put("Сейшельские Острова", "SYC");
        RU_TO_ISO3.put("Сенегал", "SEN");
        RU_TO_ISO3.put("Сент-Винсент и Гренадины", "VCT");
        RU_TO_ISO3.put("Сент-Китс и Невис", "KNA");
        RU_TO_ISO3.put("Сент-Люсия", "LCA");
        RU_TO_ISO3.put("Сербия", "SRB");
        RU_TO_ISO3.put("Сингапур", "SGP");
        RU_TO_ISO3.put("Сирия", "SYR");
        RU_TO_ISO3.put("Словакия", "SVK");
        RU_TO_ISO3.put("Словения", "SVN");
        RU_TO_ISO3.put("Соломоновы Острова", "SLB");
        RU_TO_ISO3.put("Сомали", "SOM");
        RU_TO_ISO3.put("Судан", "SDN");
        RU_TO_ISO3.put("Южный Судан", "SSD");
        RU_TO_ISO3.put("Суринам", "SUR");
        RU_TO_ISO3.put("США", "USA");
        RU_TO_ISO3.put("Соединённые Штаты Америки", "USA");
        RU_TO_ISO3.put("Сьерра-Леоне", "SLE");
        RU_TO_ISO3.put("Таджикистан", "TJK");
        RU_TO_ISO3.put("Таиланд", "THA");
        RU_TO_ISO3.put("Танзания", "TZA");
        RU_TO_ISO3.put("Того", "TGO");
        RU_TO_ISO3.put("Тонга", "TON");
        RU_TO_ISO3.put("Тринидад и Тобаго", "TTO");
        RU_TO_ISO3.put("Тунис", "TUN");
        RU_TO_ISO3.put("Туркменистан", "TKM");
        RU_TO_ISO3.put("Турция", "TUR");
        RU_TO_ISO3.put("Тувалу", "TUV");
        RU_TO_ISO3.put("Уганда", "UGA");
        RU_TO_ISO3.put("Узбекистан", "UZB");
        RU_TO_ISO3.put("Украина", "UKR");
        RU_TO_ISO3.put("Уругвай", "URY");
        RU_TO_ISO3.put("Фиджи", "FJI");
        RU_TO_ISO3.put("Филиппины", "PHL");
        RU_TO_ISO3.put("Финляндия", "FIN");
        RU_TO_ISO3.put("Франция", "FRA");
        RU_TO_ISO3.put("Хорватия", "HRV");
        RU_TO_ISO3.put("ЦАР", "CAF");
        RU_TO_ISO3.put("Центральноафриканская Республика", "CAF");
        RU_TO_ISO3.put("Чад", "TCD");
        RU_TO_ISO3.put("Черногория", "MNE");
        RU_TO_ISO3.put("Чехия", "CZE");
        RU_TO_ISO3.put("Чили", "CHL");
        RU_TO_ISO3.put("Швейцария", "CHE");
        RU_TO_ISO3.put("Швеция", "SWE");
        RU_TO_ISO3.put("Шри-Ланка", "LKA");
        RU_TO_ISO3.put("Эквадор", "ECU");
        RU_TO_ISO3.put("Экваториальная Гвинея", "GNQ");
        RU_TO_ISO3.put("Эритрея", "ERI");
        RU_TO_ISO3.put("Эстония", "EST");
        RU_TO_ISO3.put("Эфиопия", "ETH");
        RU_TO_ISO3.put("ЮАР", "ZAF");
        RU_TO_ISO3.put("Южно-Африканская Республика", "ZAF");
        RU_TO_ISO3.put("Южная Осетия", null);
        RU_TO_ISO3.put("Ямайка", "JAM");
        RU_TO_ISO3.put("Япония", "JPN");
        RU_TO_ISO3.put("Северная Македония", "MKD");
        RU_TO_ISO3.put("Косово", "XKX");
        RU_TO_ISO3.put("Палестина", "PSE");
        RU_TO_ISO3.put("Тайвань", "TWN");
        RU_TO_ISO3.put("Абхазия", null);
    }

    static {
        ISO3_TO_ISO2.put("AFG", "af");
        ISO3_TO_ISO2.put("AGO", "ao");
        ISO3_TO_ISO2.put("ALB", "al");
        ISO3_TO_ISO2.put("AND", "ad");
        ISO3_TO_ISO2.put("ARE", "ae");
        ISO3_TO_ISO2.put("ARG", "ar");
        ISO3_TO_ISO2.put("ARM", "am");
        ISO3_TO_ISO2.put("ATG", "ag");
        ISO3_TO_ISO2.put("AUS", "au");
        ISO3_TO_ISO2.put("AUT", "at");
        ISO3_TO_ISO2.put("AZE", "az");
        ISO3_TO_ISO2.put("BDI", "bi");
        ISO3_TO_ISO2.put("BEL", "be");
        ISO3_TO_ISO2.put("BEN", "bj");
        ISO3_TO_ISO2.put("BFA", "bf");
        ISO3_TO_ISO2.put("BGD", "bd");
        ISO3_TO_ISO2.put("BGR", "bg");
        ISO3_TO_ISO2.put("BHR", "bh");
        ISO3_TO_ISO2.put("BHS", "bs");
        ISO3_TO_ISO2.put("BIH", "ba");
        ISO3_TO_ISO2.put("BLR", "by");
        ISO3_TO_ISO2.put("BLZ", "bz");
        ISO3_TO_ISO2.put("BOL", "bo");
        ISO3_TO_ISO2.put("BRA", "br");
        ISO3_TO_ISO2.put("BRB", "bb");
        ISO3_TO_ISO2.put("BRN", "bn");
        ISO3_TO_ISO2.put("BTN", "bt");
        ISO3_TO_ISO2.put("BWA", "bw");
        ISO3_TO_ISO2.put("CAF", "cf");
        ISO3_TO_ISO2.put("CAN", "ca");
        ISO3_TO_ISO2.put("CHE", "ch");
        ISO3_TO_ISO2.put("CHL", "cl");
        ISO3_TO_ISO2.put("CHN", "cn");
        ISO3_TO_ISO2.put("CIV", "ci");
        ISO3_TO_ISO2.put("CMR", "cm");
        ISO3_TO_ISO2.put("COD", "cd");
        ISO3_TO_ISO2.put("COG", "cg");
        ISO3_TO_ISO2.put("COL", "co");
        ISO3_TO_ISO2.put("COM", "km");
        ISO3_TO_ISO2.put("CPV", "cv");
        ISO3_TO_ISO2.put("CRI", "cr");
        ISO3_TO_ISO2.put("CUB", "cu");
        ISO3_TO_ISO2.put("CYP", "cy");
        ISO3_TO_ISO2.put("CZE", "cz");
        ISO3_TO_ISO2.put("DEU", "de");
        ISO3_TO_ISO2.put("DJI", "dj");
        ISO3_TO_ISO2.put("DMA", "dm");
        ISO3_TO_ISO2.put("DNK", "dk");
        ISO3_TO_ISO2.put("DOM", "do");
        ISO3_TO_ISO2.put("DZA", "dz");
        ISO3_TO_ISO2.put("ECU", "ec");
        ISO3_TO_ISO2.put("EGY", "eg");
        ISO3_TO_ISO2.put("ERI", "er");
        ISO3_TO_ISO2.put("ESP", "es");
        ISO3_TO_ISO2.put("EST", "ee");
        ISO3_TO_ISO2.put("ETH", "et");
        ISO3_TO_ISO2.put("FIN", "fi");
        ISO3_TO_ISO2.put("FJI", "fj");
        ISO3_TO_ISO2.put("FRA", "fr");
        ISO3_TO_ISO2.put("FSM", "fm");
        ISO3_TO_ISO2.put("GAB", "ga");
        ISO3_TO_ISO2.put("GBR", "gb");
        ISO3_TO_ISO2.put("GEO", "ge");
        ISO3_TO_ISO2.put("GHA", "gh");
        ISO3_TO_ISO2.put("GIN", "gn");
        ISO3_TO_ISO2.put("GMB", "gm");
        ISO3_TO_ISO2.put("GNB", "gw");
        ISO3_TO_ISO2.put("GNQ", "gq");
        ISO3_TO_ISO2.put("GRC", "gr");
        ISO3_TO_ISO2.put("GRD", "gd");
        ISO3_TO_ISO2.put("GTM", "gt");
        ISO3_TO_ISO2.put("GUY", "gy");
        ISO3_TO_ISO2.put("HND", "hn");
        ISO3_TO_ISO2.put("HRV", "hr");
        ISO3_TO_ISO2.put("HTI", "ht");
        ISO3_TO_ISO2.put("HUN", "hu");
        ISO3_TO_ISO2.put("IDN", "id");
        ISO3_TO_ISO2.put("IND", "in");
        ISO3_TO_ISO2.put("IRL", "ie");
        ISO3_TO_ISO2.put("IRN", "ir");
        ISO3_TO_ISO2.put("IRQ", "iq");
        ISO3_TO_ISO2.put("ISL", "is");
        ISO3_TO_ISO2.put("ISR", "il");
        ISO3_TO_ISO2.put("ITA", "it");
        ISO3_TO_ISO2.put("JAM", "jm");
        ISO3_TO_ISO2.put("JOR", "jo");
        ISO3_TO_ISO2.put("JPN", "jp");
        ISO3_TO_ISO2.put("KAZ", "kz");
        ISO3_TO_ISO2.put("KEN", "ke");
        ISO3_TO_ISO2.put("KGZ", "kg");
        ISO3_TO_ISO2.put("KHM", "kh");
        ISO3_TO_ISO2.put("KIR", "ki");
        ISO3_TO_ISO2.put("KNA", "kn");
        ISO3_TO_ISO2.put("KOR", "kr");
        ISO3_TO_ISO2.put("KWT", "kw");
        ISO3_TO_ISO2.put("LAO", "la");
        ISO3_TO_ISO2.put("LBN", "lb");
        ISO3_TO_ISO2.put("LBR", "lr");
        ISO3_TO_ISO2.put("LBY", "ly");
        ISO3_TO_ISO2.put("LCA", "lc");
        ISO3_TO_ISO2.put("LIE", "li");
        ISO3_TO_ISO2.put("LKA", "lk");
        ISO3_TO_ISO2.put("LSO", "ls");
        ISO3_TO_ISO2.put("LTU", "lt");
        ISO3_TO_ISO2.put("LUX", "lu");
        ISO3_TO_ISO2.put("LVA", "lv");
        ISO3_TO_ISO2.put("MAR", "ma");
        ISO3_TO_ISO2.put("MCO", "mc");
        ISO3_TO_ISO2.put("MDA", "md");
        ISO3_TO_ISO2.put("MDG", "mg");
        ISO3_TO_ISO2.put("MDV", "mv");
        ISO3_TO_ISO2.put("MEX", "mx");
        ISO3_TO_ISO2.put("MHL", "mh");
        ISO3_TO_ISO2.put("MKD", "mk");
        ISO3_TO_ISO2.put("MLI", "ml");
        ISO3_TO_ISO2.put("MLT", "mt");
        ISO3_TO_ISO2.put("MMR", "mm");
        ISO3_TO_ISO2.put("MNE", "me");
        ISO3_TO_ISO2.put("MNG", "mn");
        ISO3_TO_ISO2.put("MOZ", "mz");
        ISO3_TO_ISO2.put("MRT", "mr");
        ISO3_TO_ISO2.put("MUS", "mu");
        ISO3_TO_ISO2.put("MWI", "mw");
        ISO3_TO_ISO2.put("MYS", "my");
        ISO3_TO_ISO2.put("NAM", "na");
        ISO3_TO_ISO2.put("NER", "ne");
        ISO3_TO_ISO2.put("NGA", "ng");
        ISO3_TO_ISO2.put("NIC", "ni");
        ISO3_TO_ISO2.put("NLD", "nl");
        ISO3_TO_ISO2.put("NOR", "no");
        ISO3_TO_ISO2.put("NPL", "np");
        ISO3_TO_ISO2.put("NRU", "nr");
        ISO3_TO_ISO2.put("NZL", "nz");
        ISO3_TO_ISO2.put("OMN", "om");
        ISO3_TO_ISO2.put("PAK", "pk");
        ISO3_TO_ISO2.put("PAN", "pa");
        ISO3_TO_ISO2.put("PER", "pe");
        ISO3_TO_ISO2.put("PHL", "ph");
        ISO3_TO_ISO2.put("PLW", "pw");
        ISO3_TO_ISO2.put("PNG", "pg");
        ISO3_TO_ISO2.put("POL", "pl");
        ISO3_TO_ISO2.put("PRK", "kp");
        ISO3_TO_ISO2.put("PRT", "pt");
        ISO3_TO_ISO2.put("PRY", "py");
        ISO3_TO_ISO2.put("PSE", "ps");
        ISO3_TO_ISO2.put("QAT", "qa");
        ISO3_TO_ISO2.put("ROU", "ro");
        ISO3_TO_ISO2.put("RUS", "ru");
        ISO3_TO_ISO2.put("RWA", "rw");
        ISO3_TO_ISO2.put("SAU", "sa");
        ISO3_TO_ISO2.put("SDN", "sd");
        ISO3_TO_ISO2.put("SEN", "sn");
        ISO3_TO_ISO2.put("SGP", "sg");
        ISO3_TO_ISO2.put("SLB", "sb");
        ISO3_TO_ISO2.put("SLE", "sl");
        ISO3_TO_ISO2.put("SLV", "sv");
        ISO3_TO_ISO2.put("SMR", "sm");
        ISO3_TO_ISO2.put("SOM", "so");
        ISO3_TO_ISO2.put("SRB", "rs");
        ISO3_TO_ISO2.put("SSD", "ss");
        ISO3_TO_ISO2.put("STP", "st");
        ISO3_TO_ISO2.put("SUR", "sr");
        ISO3_TO_ISO2.put("SVK", "sk");
        ISO3_TO_ISO2.put("SVN", "si");
        ISO3_TO_ISO2.put("SWE", "se");
        ISO3_TO_ISO2.put("SWZ", "sz");
        ISO3_TO_ISO2.put("SYC", "sc");
        ISO3_TO_ISO2.put("SYR", "sy");
        ISO3_TO_ISO2.put("TCD", "td");
        ISO3_TO_ISO2.put("TGO", "tg");
        ISO3_TO_ISO2.put("THA", "th");
        ISO3_TO_ISO2.put("TJK", "tj");
        ISO3_TO_ISO2.put("TKM", "tm");
        ISO3_TO_ISO2.put("TLS", "tl");
        ISO3_TO_ISO2.put("TON", "to");
        ISO3_TO_ISO2.put("TTO", "tt");
        ISO3_TO_ISO2.put("TUN", "tn");
        ISO3_TO_ISO2.put("TUR", "tr");
        ISO3_TO_ISO2.put("TUV", "tv");
        ISO3_TO_ISO2.put("TWN", "tw");
        ISO3_TO_ISO2.put("TZA", "tz");
        ISO3_TO_ISO2.put("UGA", "ug");
        ISO3_TO_ISO2.put("UKR", "ua");
        ISO3_TO_ISO2.put("URY", "uy");
        ISO3_TO_ISO2.put("USA", "us");
        ISO3_TO_ISO2.put("UZB", "uz");
        ISO3_TO_ISO2.put("VAT", "va");
        ISO3_TO_ISO2.put("VCT", "vc");
        ISO3_TO_ISO2.put("VEN", "ve");
        ISO3_TO_ISO2.put("VNM", "vn");
        ISO3_TO_ISO2.put("VUT", "vu");
        ISO3_TO_ISO2.put("WSM", "ws");
        ISO3_TO_ISO2.put("XKX", "xk");
        ISO3_TO_ISO2.put("YEM", "ye");
        ISO3_TO_ISO2.put("ZAF", "za");
        ISO3_TO_ISO2.put("ZMB", "zm");
        ISO3_TO_ISO2.put("ZWE", "zw");
    }

    public static String getIso2ByRussianName(String russianName) {
        String iso3 = getIso3ByRussianName(russianName);
        if (iso3 == null) return null;
        return ISO3_TO_ISO2.get(iso3.toUpperCase());
    }

    public static String getFlagUrlByRussianName(String russianName) {
        String iso2 = getIso2ByRussianName(russianName);
        if (iso2 == null || iso2.isEmpty()) return null;
        return "https://flagcdn.com/w320/" + iso2 + ".png";
    }

    public static String getEnglishNameByRussianName(String russianName) {
        String iso2 = getIso2ByRussianName(russianName);
        if (iso2 == null || iso2.isEmpty()) return null;
        String english = new Locale("", iso2.toUpperCase()).getDisplayCountry(Locale.ENGLISH);

        if (english == null || english.isEmpty() || english.equalsIgnoreCase(iso2)) return null;
        return english;
    }

    public static String getNameForExternal(String russianName) {
        String english = getEnglishNameByRussianName(russianName);
        return (english != null && !english.isEmpty()) ? english : russianName;
    }

    public static String getIso3ByRussianName(String russianName) {
        if (russianName == null) return null;
        return RU_TO_ISO3.get(russianName.trim());
    }
}
